.\" -*- nroff -*-
.TH FROTZ 6 2.32
.SH NAME
frotz \- interpreter for all Infocom games
.SH SYNOPSIS
.B frotz
.RI [ options "] " file
.SH DESCRIPTION
.B Frotz
is a Z-machine interpreter.  The Z-machine was a virtual machine designed
by Infocom to run all of their text adventures.  It went through multiple
revisions during the lifetime of the company, and two further revisions
(V7 and V8) were created by Graham Nelson after the company's demise.
The specification is now quite well documented; this version of frotz
supports version 1.0.
.SH OPTIONS
.TP
.B \-a
Watch attribute setting.  Setting and clearing of attributes on objects
will be noted in debugging messages.
.TP
.B \-A
Watch attribute testing.  Every time the z-machine test an attribute value,
the test and the result will be reported.
.TP
.B \-b N
Sets the default background color.  N corresponds to one of the Z-machine
colors, which are as follows:
.br
2  =  black   3 = red       4 = green    5 = yellow
.br
6  =  blue    7 = magenta   8 = cyan     9 = white
.br
If color support is disabled in the binary, or not
available on your terminal, this option does nothing.
.TP
.B \-c N
Sets the number of context lines used.  By default, after a ``[MORE]''
prompt, and assuming there is enough output pending, frotz will allow all
the currently visible lines to scroll off the screen before prompting
again.  This switch specifies how many lines of text frotz will hold
over and display at the top of the next screen.
.TP
.B \-d
Disables color.  If frotz discovers that your terminal has color support,
it will enable it by default.  This switch overrides that behavior.
.TP
.B \-f N
Sets the default foreground color.  N is a number corresponding to one of
the Z-machine colors, as listed above.  If color support is disabled in
the binary, or not available on your terminal, this option does nothing.
.TP
.B \-h N
Manually sets the screen height.  Though most curses libraries are intelligent
enough to determine the current width from the terminal, it may sometimes
be necessary to use this option to override the default.
.TP
.B \-i
Ignore runtime errors.  Set this switch and Frotz no longer worries about
anything the game tries to do. This can help you to get around fatal errors.
.TP
.B \-l N
Sets the left margin, for those who might have specific formatting needs.
.TP
.B \-o
Watch object movement.  This option enables debugging messages from the
interpreter which detail the moving of objects in the object tree.
.TP
.B \-O
Watch object location.  These debugging messages detail the locations of
objects in the object tree.
.TP
.B \-p
Plain ASCII output only.  This inhibits the output of accented letters
and other characters from the Latin-1 character set, replacing them with
reasonable alternatives.  This may be necessary on devices lacking these
characters.
.TP
.B \-P
Alter the piracy opcode.  The piracy opcode was never used by Infocom, and
this switch is only useful for those who like to toy around with Z-code.
.TP
.B \-r N
Sets the right margin.
.TP
.B \-s N
Set the random number seed value.  The given seed value is used as the initial
seed value on every restart. This is helpful for testing games like
.B Curses
which make random decisions before the first input (such that the hot
key Alt\-S does not really help).
.TP
.B \-S N
Set the transcript width.  By default your transscript files are formatted
to a width of 80 columns per line, regardless of the current screen width.
This switch allows you to change this setting. In particular, use \-S 0
to deactivate automatic line splitting in transscript files.
.TP
.B \-t
Sets the z-machine's
.I Tandy bit,
which may affect the behavior of certain Infocom games.  For example,
Zork I pretends not to have sequals, and Witness has it's language
toned down.
.TP
.B \-u N
Sets the number of slots available for frotz's multiple undo hotkey (see
below).  This defaults to twenty, which should be sufficient for most
purposes.  Setting too high a number here may be dangerous on machines
with limited memory.
.TP
.B \-w N
Manually sets the screen width.  Again, this should not be necessary
except in special circumstances.
.TP
.B \-x
Expand the abbreviations "g","x", and "z" to "again", "examine", and "wait".
This switch was made for old Infocom games that lack the common
abbreviations introduced in later games. Use it with caution: A
few games might use "g", "x" or "z" for different purposes.
.SH ENVIRONMENT
If the INFOCOM_PATH environment variable is defined, frotz will search
those paths for game files.
.SH "SEE ALSO"
.SH CAVEATS
.SH BUGS
This program has no bugs.  no bugs.  no bugs.  no *WHAP* thank you.
.SH AUTHOR
.B Frotz
was written by Stefan Jokisch in 1995-7.  The unix port (and this man
page) were done by Galen Hazelwood.
